### ISSUE TITLE
Directory Error

### ISSUE THREAD

**Issue by Rudy34160** [Data-Science-Knowledge-Center-Nova-SBE/food-aesthetics#1]
Hi, 

I've followed the directions in the readme, but I'm getting the following error:

_C:\Ai_Folder\Aesthetic score\food-aesthetics-main>run.py Users/Admin/Downloads/Marilyn/Test score
Traceback (most recent call last):
  File "C:\Ai_Folder\Aesthetic score\food-aesthetics-main\run.py", line 20, in <module>
    args = parser.parse_args()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 2082, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 2038, in consume_positionals
    take_action(action, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1927, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 2462, in _get_values
    value = self._get_value(action, arg_string)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 2495, in _get_value
    result = type_func(arg_string)
  File "C:\Ai_Folder\Aesthetic score\food-aesthetics-main\run.py", line 12, in dir_path
    raise NotADirectoryError(string)
NotADirectoryError: Users/Admin/Downloads/Marilyn/Test_

**Comment by iamalegambetti** [comment]
Hi @Rudy34160,

It looks like you are using a Unix (Linux/Mac) absolute path as the image folder path while you are on a Windows machine. So, you should use a Windows path instead. For example, if you have stored the images in an "Images" folder within your "Documents", you can use use "C:\Documents\Images" as an absolute path.
I hope this clarifies.

Best,
Alessandro

**Comment by Rudy34160** [comment]
> Hi @Rudy34160,
> 
> It looks like you are using a Unix (Linux/Mac) absolute path as the image folder path while you are on a Windows machine. So, you should use a Windows path instead. For example, if you have stored the images in an "Images" folder within your "Documents", you can use use "C:\Documents\Images" as an absolute path. I hope this clarifies.
> 
> Best, Alessandro

Thank you for the answer !

Is it possible to modify the run.py to be able to assign a score to images that are not in .jpeg format?

**Comment by iamalegambetti** [comment]
Dear @Rudy34160 ,

The code has been developed for working with .jpeg images. However, you may delete line 29 from the run.py file, and check whether it works with .png images. 

However, for more robust results, my suggestion is to convert your images to .jpeg. 

I hope this clarifies.

Best,
Alessandro
